version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18             
  pre_build:
    commands:
      - npm install -f
      - echo 'installed npm successfully'
  build:
    commands:
      - npm run build   # Runs the build script defined in package.json
      - echo 'npm run build successful'
artifacts:
  files: 
    - '**/*'              # Includes all files and subdirectories from the root directory
    - 'appspec.yml'          # Includes the appspec.yml file
    - 'scripts/**'  
